src/app.py
from flask import Flask, render_template
from src.common.database import Database
from src.models.users.views import user_blueprint
from src.models.stores.views import store_blueprint
from src.models.alerts.views import alert_blueprint


app = Flask(__name__)
app.config.from_object('src.config')
app.secret_key = "123"


@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def home():
    return render_template('home.html')

# @app.route('/')


# from src.models.users.views import user_blueprint
app.register_blueprint(user_blueprint, url_prefix="/users")

# from src.models.alerts.views import alert_blueprint
app.register_blueprint(alert_blueprint, url_prefix="/alerts")

# from src.models.stores.views import store_blueprint
app.register_blueprint(store_blueprint, url_prefix="/stores")


src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, url_for
from werkzeug.utils import redirect

import src.models.users.decorators as user_decorators
from src.models.alerts.alert import Alert
from src.models.items.item import Item

alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/')
def index():
    return render_template('alerts/alert_home.html')


@alert_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_login  # redirects the user to 'users.Login' if session['email'] is None
def create_alert():
    if request.method == "POST":
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()   #  this already saves to mongo

#     What happens if its a GET request
    return render_template('alerts/new_alert.html')


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@user_decorators.requires_login
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)
    if request.method == 'POST':
        price_limit = float(request.form['price_limit'])

        alert.price_limit = price_limit
        alert.save_to_mongo()

        return redirect(url_for('users.user_alerts'))
    return render_template('alerts/edit_alert.html', alert=alert)


@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template('alerts/alert.html', alert=alert)


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))


src/models/items/views.py
from flask import Blueprint

item_blueprint = Blueprint('items', __name__)


@item_blueprint.route('/item/<string:name>')
def item_page():
    pass

src/models/stores/views.py
from flask import Blueprint, render_template, request, json, url_for
from werkzeug.utils import redirect
import src.models.users.decorators as user_decorators

from src.models.stores.store import Store

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template('stores/store_index.html', stores=stores)


@store_blueprint.route('/store/<string:store_id>')
def store_page(store_id):
    return render_template('stores/store.html', store=Store.get_by_id(store_id))


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions
def edit_store(store_id):
    store = Store.get_by_id(store_id)

    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('stores/edit_store.html', store=store)


@store_blueprint.route('/delete/<string:store_id>')
@user_decorators.requires_admin_permissions
def delete_store(store_id):
    Store.get_by_id(store_id).delete()
    return redirect(url_for('.index'))

@store_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name, url_prefix, tag_name, query).save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('stores/create_store.html')

src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template, flash
from werkzeug.utils import redirect
import src.models.users.decorators as user_decorators
from src.models.users.user import User
import src.models.users.errors as UserErrors

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        #  Check login if valid
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.html")


@user_blueprint.route('/register', methods=['GET', "POST"])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.html")


@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    alerts = user.get_alerts()
    return render_template('users/alerts.html', alerts=alerts, email=user.email)


@user_blueprint.route('/logout')
def user_logout():
    session['email'] = None
    return redirect(url_for('home'))


@user_blueprint.route('/check_alerts/<string:user_id>')
def check_user_alerts():
    pass

src/templates/alerts/alert.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header w3-container w3-animate-top">
        <h1>Alert <small id="small">for '{{ alert.item.name }}'</small></h1>
    </div>
    <div id="alert-info" class="w3-container w3-animate-left">
        <p>Price you want: $<strong>{{ alert.price_limit }}</strong></p>
        <p>Last price found: $<strong>{{ alert.item.price }}</strong></p>
        <p>Last checked on: <strong>{{ alert.last_checked.strftime('%m-%d-%Y at %H:%M') }}</strong></p>
    </div>
    <div class="panel panel-default w3-container w3-animate-bottom" id="alert-op">
        <div class="panel-body">
            <a class="btn btn-default" href="{{ alert.item.url }}" role="button" target="_blank">Visit Site</a>
            <a class="btn btn-warning" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" role="button">Edit Alert</a>
            {% if alert.active %}
                <a class="btn btn-danger" href="{{ url_for('alerts.deactivate_alert', alert_id=alert._id) }}" role="button">Deactivate Alert</a>
            {% else %}
                <a class="btn btn-success" href="{{ url_for('alerts.activate_alert', alert_id=alert._id) }}" role="button">Activate Alert</a>
                <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}" role="button">Delete Alert</a>
            {% endif %}
            <a class="btn btn-warning" href="{{ url_for('alerts.check_alert_price', alert_id=alert._id) }}" role="button">Check Price</a>
        </div>
    </div>
{% endblock %}

src/templates/alerts/alert_home.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbo w3-container w3-animate-opacity" id="alerts_home">
        <h1 id="jumboh">What are Alerts</h1>
        <br>
        <p>Alerts are simple and time saving. They are reminders of the item you'd like to keep track of.
        You set a specific price you are willing to buy the item and the website will do the rest.</p>
        <br>
        {% if session['email'] %}
            <div class="wrapper">
                <a href="{{ url_for('users.user_alerts') }}" class="btn btn-success"> My Alerts</a>
            </div>
        {% else %}
            <div class="alerts-btn">
                <a href="{{ url_for('users.register_user') }}" class="btn btn-primary"> Register!</a>
                <a href="{{ url_for('users.login_user') }}" class="btn btn-success"> Login</a>
            </div>
        {% endif %}
    </div>


{% endblock %}

src/templates/alerts/edit_alert.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header w3-container w3-animate-top">
        <h1>Edit Alert <small>{{ alert.name }}</small></h1>
    </div>
    <div class="form-size w3-container w3-animate-bottom">
        <form method="post">
            <div class="form-group">
                <label for="name">Alert/Item name/</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="{{ alert.item.name }}" disabled>
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="{{ alert.item.url }}" disabled>
            </div>
            <div class="form-group">
                <label for="price_limit">Alert limit</label>
                <input type="float" class="form-control" id="price_limit" name="price_limit" placeholder="Price limit" value="{{ alert.price_limit }}" aria-describedby="priceLimitBlock">
                <p id="priceLimitBlock" class="help-block">We'll send you an email once the price you entered here is matched or the price is lower than set price</p>
            </div>
            <button type="submit" class="btn btn-success">Update!</button>
        </form>
    </div>
{% endblock %}

src/templates/alerts/new_alert.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header w3-container w3-animate-opacity">
        <h1>Create Alert</h1>
    </div>
    <div class="form-size w3-container w3-animate-opacity">
        <form method="post">
            <div class="form-group">
                <label for="name">Alert/Item name/</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="http://...">
            </div>
            <div class="form-group">
                <label for="price_limit">Alert limit</label>
                <input type="float" class="form-control" id="price_limit" name="price_limit" placeholder="Price limit" aria-describedby="priceLimitBlock">
                <p id="priceLimitBlock" class="help-block">We'll send you an email once the price you entered here is matched or the price is lower than set price</p>
            </div>
            <button type="submit" class="btn btn-success">Create!</button>
        </form>
    </div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your Item pricing service</title>
    {% include 'html_dependencies.html' %}
</head>
<body>
    <div id="body-div">
        <nav class="navbar navbar-default" id="nav-bar">
            <div class="container">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <div class="navbar-header">
                    <a class="navbar-brand" href="/" title="Home">Pricing</a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url_for('stores.index') }}">Stores</a></li>
                        <li><a href="{{ url_for('alerts.index') }}">Alerts</a></li>
                    </ul>
                    {% if session['email'] %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{{ url_for('users.user_alerts') }}"><span class="glyphicon glyphicon-bell"></span> My Alerts</a></li>
                            <li><a href="{{ url_for('users.user_logout') }}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                        </ul>
                    {% else %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{{ url_for('users.register_user') }}"><span class="glyphicon glyphicon-user"></span> Register!</a></li>
                            <li><a href="{{ url_for('users.login_user') }}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
        <div class="content container">
            {% block content %}

            {% endblock %}
        </div>
    </div>
    <div id="footer">
        <p>Developed by: Pablo Hernandez</p>
        <p>Code for this website: <a href="https://github.com/prh90/python/tree/master/web_course_work/full_stack/project/src" target="_blank">GITHUB</a></p>
    </div>
</body>
</html>

src/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="home-ex w3-container w3-animate-opacity" id="home">
      <h1 id="home-h1">Alert Pricing Service</h1>
        <br>
        <p>The service includes a scan of websites to alert you of price drop that interests you</p>
        <p>Just sign up, and get started by adding the URL you wish to track and we will do the rest!</p>
        {% if session['email'] %}
            <br>
            <p>Welcome Back <strong>{{session['email']}}!</strong></p>
        {% else %}
            <br>
            <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign up</a></p>
        {% endif %}
    </div>
{% endblock %}

src/templates/html_dependencies.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for( 'static', filename='css/style.css' ) }}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script type=text/javascript src="{{url_for('static', filename='js/jquery.js') }}"></script>

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

src/templates/stores/create_store.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header w3-container w3-animate-top">
        <h1>Create Store</h1>
    </div>
    <div class="form-size w3-container w3-animate-bottom">
        <form method="post">
            <div class="form-group">
                <label for="name">Store name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Store Name">
            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://...." aria-describedby="storeURLPrefixHelp">
                <span id="storeURLPrefixHelp" class="help-block">What characters do URL's of all items in this online store start with? </span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag Name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="span" aria-describedby="storeTagName">
                <span id="storeTagName" class="help-block">What is the HTML tag of the item that contains the item price? (usually <code>span</code>) </span>
            </div>
            <div class="form-group">
                <label for="query">Search Query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "price-now"}' value='{"id": "price-now"}'  aria-describedby="queryHelpBlock">
                <span id="queryHelpBlock" class="help-block">What JSON query would we have to do to find the specific tag with the price? Remember to use double quotation marks</span>
            </div>
            <button type="submit" class="btn btn-default">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/stores/edit_store.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header w3-container w3-animate-top">
        <h1>Edit Store</h1>
    </div>
    <div class="form-size w3-container w3-animate-bottom">
        <form method="post">
            <div class="form-group">
                <label for="name">Store name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Store Name" value="{{ store.name }}">
            </div>
            <div class="form-group">
                <label for="url_prefix">Store URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://...." value="{{ store.url_prefix }}" aria-describedby="storeURLPrefixHelp">
                <span id="storeURLPrefixHelp" class="help-block">What characters do URL's of all items in this online store start with? </span>
            </div>
            <div class="form-group">
                <label for="tag_name">Tag Name</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="{{ store.tag_name }}" aria-describedby="storeTagName">
                <span id="storeTagName" class="help-block">What is the HTML tag of the item that contains the item price? (usually <code>span</code>) </span>
            </div>
            <div class="form-group">
                <label for="query">Search Query</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "price-now"}' value="{{ store.query | tojson }}"  aria-describedby="queryHelpBlock">
                <span id="queryHelpBlock" class="help-block">What JSON query would we have to do to find the specific tag with the price? Remember to use double quotation marks</span>
            </div>
            <button type="submit" class="btn btn-warning">Update</button>
            <a href="{{ url_for('stores.store_page', store_id=store._id) }}" role="button" class="btn btn-default">Cancel</a>
        </form>
    </div>
{% endblock %}

src/templates/stores/store.html
{% extends "base.html" %}
{% block content %}
<div class="page-header w3-container w3-animate-left">
    <h1>Store
        <small id="small">{{ store.name }}</small>
    </h1>
</div>
<p class="w3-container w3-animate-left">All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p>
{% if session['email'] in config.ADMINS %}
<div class="panel panel-default w3-container w3-animate-right" id="store-op">
    <div class="panel-body">
        <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id) }}" role="button">Edit
            Store</a>
        <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">Delete
            Store</a>
    </div>
</div>
{% endif %}

{% endblock %}

src/templates/stores/store_index.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header w3-container w3-animate-left">
        <h1>Stores <small id="small">list of supported stores</small></h1>
    </div>
    <div class="list-group w3-container w3-animate-right">
        {% for store in stores %}
            <a href="{{ url_for('stores.store_page', store_id=store._id)}}" class="list-group-item">
            <h4 class="list-group-item-title">{{ store.name }}</h4>
            <p class="list-group-item-text">All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p></a>
        {% endfor %}
    </div>
    {% if session['email'] in config.ADMINS %}
        <a class="btn btn-success w3-container w3-center w3-animate-bottom" href="{{ url_for('stores.create_store') }}">
            <span class="glyphicon glyphicon-plus"></span> Create New
        </a>
    {% else %}
        <p class="store-add"> Stores are being constantly updated, Stay tuned for your preferred store! </p>
    {% endif %}
{% endblock %}

src/templates/users/alerts.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header w3-container w3-animate-right">
        <h1>{{ email }}'s Alerts <small id="alert-des">Showing all existing alerts</small></h1>
    </div>
    <div class="list-group w3-container w3-animate-left">
        {% for alert in alerts %}
            <a href="{{ url_for('alerts.get_alert_page', alert_id=alert._id) }}" class="list-group-item list-group-item-success {{'list-group-item list-group-item-danger' if not alert.active else ''}}">
                <h4 class="list-group-item-heading">Alert for {{ alert.item.name }}</h4>
                <p class="list-group-item-text">Last price found: <strong>{{ alert.item.price }}</strong><br>
                    Last checked on <strong>{{ alert.last_checked.strftime("%m-%d-%Y at %H:%M") }}</strong></p>
                <p class="list-group-item-text">Alert status: <strong>{{ 'Inactive' if not alert.active else 'Active' }}</strong></p>
            </a>
        {% endfor %}
    </div>
    <a class="btn btn-success w3-container w3-animate-bottom" href="{{ url_for('alerts.create_alert') }}"><span class="glyphicon glyphicon-plus"></span> Create Alert</a>

{% endblock %}

src/templates/users/login.html
{% extends "base.html" %}
{% block content %}
    <div class="form-size w3-container w3-animate-opacity">
        <h1 id="jumboh">Login</h1>
        <form action="{{ url_for('users.login_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email Address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Login</button>
            <br>
        </form>
    </div>
{% endblock %}

src/templates/users/register.html
{% extends "base.html" %}
{% block content %}
    <div class="form-size w3-container w3-animate-opacity">
        <h1 id="jumboh">Register</h1>
        <form action="{{ url_for('users.register_user') }}" method="post">
            <div class="form-group">
                <label for="email">Email Address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Sing up</button>
            <br>
        </form>
    </div>
{% endblock %}